# Generated by Django 6.1 on 2026-08-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_account_id_alter_action_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.symptom'),
        ),
    ]
